name: Daily Automated Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add a daily commit by 22f3002631@ds.study.iitm.ac.in
        run: |
          git config user.name "GitHub Actions"
          git config user.email "22f3002631@ds.study.iitm.ac.in"
          echo "$(date): Automated daily update" >> daily_update.log
          git add daily_update.log
          git commit -m "Automated daily update: $(date)" || echo "No changes to commit"
          git push
